global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'django'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'nordicloop-backend'
